"""add language to posts

Revision ID: 65481cf96741
Revises: d0fe9baf08d0
Create Date: 2020-01-19 22:21:58.589094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65481cf96741'
down_revision = 'd0fe9baf08d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
